version: "3"

services:
  web:
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=development
      - PORT=5000
    depends_on:
      - db
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    env_file:
      - ./api/.env
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27018:27017
