version: "3"

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./api/.env

  prefect:
    build:
      context: ./prefect
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

    # depends_on:
    #   - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
